plugins {
    id 'application'
}

group = 'ru.sedmoyy'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.raphimc:MinecraftAuth:5.0.2'
}

application {
    mainClass = 'ru.sedmoyy.launcher.RadineeLauncher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('jar') {
    archiveClassifier = 'all'
    manifest {
        attributes('Main-Class': application.mainClass.get())
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
